---
# ansible-galaxy install geerlingguy.docker
 - name: Install most important Packages
   hosts: localhost
   tasks:
      - name: Start Container Tinyproxy
        docker_container:
           name: tinyproxy
           image: dannydirect/tinyproxy
           command: "ANY"
           restart_policy: always
           ports:
              - "8888:8888"

