- hosts: localhost
  tasks:
    - package: name=epel-release
      tags: rpm

    - name: Install addional RPMs
      package: name="{{ item }}"
      with_items:
        - wget
        - yum-utils
        - net-tools 
        - bash-completion
        - tree
        - gcc
        - libffi-devel
        - python-devel
        - openssl-devel
        - python-pip
        - python-wheel
        - device-mapper-persistent-data
      tags: rpm

    - name: Add Repository
      get_url:
         url: https://download.docker.com/linux/centos/docker-ce.repo
         dest: /etc/yum.repos.d/docker-ce.repo
         mode: '0644'
      tags: repo

    - name: Install Docker
      package: name="{{ item }}"
      with_items:
        - docker-ce
        - docker-compose

    - name: Service Docker
      service: name=docker state=started enabled=true
