- hosts: localhost
  vars:
    security_fail2ban_enabled: true
    security_autoupdate_enabled: true
    security_fail2ban_maxretry: 5

    # for testing
    # security_ssh_password_authentication: "yes"
    # security_ssh_permit_root_login: "no"

  roles:
    - swap
    - geerlingguy.security
    - fail2ban
